function T = buildSensitivityTable(RESULTS, cfg)
%BUILDSENSITIVITYTABLE Build Table IV using explicit tariff cases.
%
% The default sensitivity is ex-post: it applies each tariff pair to the
% computed dispatch profiles. This keeps the paper evidence reproducible and
% isolates export-price economics without adding hidden optimisation runs.

cases = cfg.tariff.sensitivityCases;
n = height(cases);

V2HOldCost = zeros(n, 1);
V2HCost = zeros(n, 1);
V2GCost = zeros(n, 1);
V2HBenefitVsOld = zeros(n, 1);
V2GBenefitVsV2H = zeros(n, 1);
V2GBenefitVsOld = zeros(n, 1);

for i = 1:n
    imp = cases.ImportTariff_GBP_per_kWh(i);
    exp = cases.ExportTariff_GBP_per_kWh(i);

    V2HOldCost(i) = local_cost(RESULTS.V2HOld, imp, 0, cfg);
    V2HCost(i) = local_cost(RESULTS.V2H, imp, exp, cfg);
    V2GCost(i) = local_cost(RESULTS.V2G, imp, exp, cfg);

    V2HBenefitVsOld(i) = V2HOldCost(i) - V2HCost(i);
    V2GBenefitVsV2H(i) = V2HCost(i) - V2GCost(i);
    V2GBenefitVsOld(i) = V2HOldCost(i) - V2GCost(i);
end

T = table( ...
    cases.TariffCase, ...
    cases.ImportTariff_GBP_per_kWh, ...
    cases.ExportTariff_GBP_per_kWh, ...
    V2HOldCost, ...
    V2HCost, ...
    V2GCost, ...
    V2HBenefitVsOld, ...
    V2GBenefitVsV2H, ...
    V2GBenefitVsOld, ...
    repmat("GBP/day", n, 1), ...
    repmat("Ex-post fixed-dispatch tariff sensitivity", n, 1), ...
    'VariableNames', { ...
    'TariffCase', ...
    'ImportTariff_GBP_per_kWh', ...
    'ExportTariff_GBP_per_kWh', ...
    'V2HOldNetCost_GBP_per_day', ...
    'V2HNetCost_GBP_per_day', ...
    'V2GNetCost_GBP_per_day', ...
    'V2HBenefitAgainstV2HOld_GBP_per_day', ...
    'V2GBenefitAgainstV2H_GBP_per_day', ...
    'V2GBenefitAgainstV2HOld_GBP_per_day', ...
    'Unit', ...
    'SensitivityMode'});

T.Properties.Description = "Table IV. Tariff sensitivity.";
end

function cost = local_cost(R, importTariff, exportTariff, cfg)
Dt = mean(diff(R.time_h(:)));
if ~isfinite(Dt) || Dt <= 0
    Dt = cfg.Dt;
end
importCost = importTariff * sum(R.P_grid_import(:))*Dt;
exportRevenue = exportTariff * sum(R.P_grid_export(:))*Dt;
cost = importCost + R.cost.batteryDegradation + R.cost.evDegradation - exportRevenue;
end

