function [summaryTable, performanceTable, physicalTable] = buildRuntimeVerificationTables(verificationSummary, cfg)
%BUILDRUNTIMEVERIFICATIONTABLES Build reviewer-ready verification tables.

regimes = cfg.project.regimeOrder;
n = numel(regimes);
rows = repmat(emptySummaryRow(), n, 1);

for k = 1:n
    key = char(regimes(k));
    if isfield(verificationSummary, key)
        rows(k) = verificationSummary.(key);
    else
        rows(k).regime = missingRegimeLabel(regimes(k));
    end
end

summaryTable = struct2table(rows);
summaryTable.Properties.Description = "Revision runtime and verification summary.";

performanceTable = table( ...
    string({rows.regime}).', ...
    [rows.timeSteps].', ...
    [rows.continuousVariables].', ...
    [rows.binaryVariables].', ...
    string({rows.solverStatus}).', ...
    [rows.optimisationRuntime_s].', ...
    [rows.verificationRuntime_s].', ...
    [rows.maxAbsBalanceResidual_kW].', ...
    [rows.rmsBalanceResidual_kW].', ...
    'VariableNames', {'Regime','T','ContinuousVariables','BinaryVariables','SolverStatus', ...
    'OptimisationTime_s','VerificationTime_s','MaxResidual_kW','RMSResidual_kW'});
performanceTable.Properties.Description = "TABLE X. Computational performance and verification summary.";

physicalTable = table( ...
    string({rows.regime}).', ...
    passFail(~[rows.boundViolation].'), ...
    passFail(~[rows.gridSimultaneityViolation].'), ...
    passFail(~[rows.evAvailabilityViolation].'), ...
    [rows.evChargeAway_kW].', ...
    [rows.evDischargeAway_kW].', ...
    [rows.costReconstructionError].', ...
    'VariableNames', {'Regime','BoundCheck','GridExclusivity','EVAvailability', ...
    'EVChargeAway_kW','EVDischargeAway_kW','CostReconstructionError'});
physicalTable.Properties.Description = "TABLE Y. Physical consistency checks.";
end

function row = emptySummaryRow()
row = struct( ...
    'regime', "", ...
    'solverStatus', "TODO: not calculated", ...
    'objectiveValue', NaN, ...
    'optimisationRuntime_s', NaN, ...
    'verificationRuntime_s', NaN, ...
    'totalRuntime_s', NaN, ...
    'timeSteps', NaN, ...
    'continuousVariables', NaN, ...
    'binaryVariables', NaN, ...
    'maxAbsBalanceResidual_kW', NaN, ...
    'rmsBalanceResidual_kW', NaN, ...
    'boundViolation', true, ...
    'gridSimultaneityViolation', true, ...
    'evAvailabilityViolation', true, ...
    'evChargeAway_kW', NaN, ...
    'evDischargeAway_kW', NaN, ...
    'costReconstructionError', NaN);
end

function label = missingRegimeLabel(regime)
if regime == "V2H"
    label = "Corrected V2H";
elseif regime == "V2HOld"
    label = "V2H-Old";
else
    label = string(regime);
end
end

function out = passFail(tf)
out = strings(numel(tf), 1);
out(tf) = "PASS";
out(~tf) = "FAIL";
end
