function T = buildMultiDayValidationSummary(DailyMetrics, cfg)
%BUILDMULTIDAYVALIDATIONSUMMARY Summarise solver and validation outcomes.

regimes = cfg.project.regimeOrder;
T = table('Size', [0 10], ...
    'VariableTypes', {'string','double','double','double','double','double','double','double','double','double'}, ...
    'VariableNames', {'Regime','TotalDays','SolverSolvedDays','CoreValidationPassDays', ...
    'FullValidationPassDays','PowerBalancePassDays','BoundsPassDays','GridLogicPassDays', ...
    'EVAvailabilityPassDays','DaysUsedInSummary'});

for r = 1:numel(regimes)
    regime = regimes(r);
    rows = DailyMetrics.Regime == regime;
    row = table(regime, sum(rows), sum(DailyMetrics.SolverSolved(rows)), ...
        sum(DailyMetrics.CoreValidationPass(rows)), ...
        sum(DailyMetrics.PowerBalancePass(rows) & DailyMetrics.BoundsPass(rows) & ...
        DailyMetrics.GridLogicPass(rows) & DailyMetrics.EVAvailabilityPass(rows)), ...
        sum(DailyMetrics.PowerBalancePass(rows)), sum(DailyMetrics.BoundsPass(rows)), ...
        sum(DailyMetrics.GridLogicPass(rows)), sum(DailyMetrics.EVAvailabilityPass(rows)), ...
        sum(DailyMetrics.UseInSummary(rows)), ...
        'VariableNames', T.Properties.VariableNames);
    T = [T; row]; %#ok<AGROW>
end
T.Properties.Description = "Multi-day validation and solver summary.";
end
